### ISSUE TITLE
can not find fossilized birth death model 

### ISSUE THREAD

**Issue by lran2008** [Taming-the-BEAST/FBD-tutorial#3]
Dear authors of FBD tutorial,

I am following the FBD tutorial for a practice. However, for the tree prior setting, I cannot find a tree model of Fossilized Birth Death Model. I attached my generated xml file (test.zip).  Could you help me find out which step I am missing? Thanks.
![20191025154711](https://user-images.githubusercontent.com/11410101/67552975-c401dc00-f73e-11e9-8be0-b006191e1b63.png)

[test.zip](https://github.com/Taming-the-BEAST/FBD-tutorial/files/3770943/test.zip)

Ran Li

**Comment by laduplessis** [comment]
Hi Ran, 

You need to first install the SA package through the BEAUti package manager, then close and restart BEAUti before the FBD model will be available. 

Louis

**Comment by lran2008** [comment]
Hi Louis,

Thanks for your help.  I installed SA package locally but without correct configration. Problem has been solved.

Thanks for your help.

Ran
