### ISSUE TITLE
"read.beast" function not found  

### ISSUE THREAD

**Issue by avvypaks** [Taming-the-BEAST/FBD-tutorial#5]
I am using the phyloch package to read my .tre file. But the "read.beast" function is not working. Is there any alternative to read my beast tree to make the geoscaled tree in the FBD model in R ?

**Comment by laduplessis** [comment]
Looks like phyloch is not supported anymore. Apparently using read.beast in the ips package solves the issue. 

Keep in mind that the read.beast function is overloaded and occurs in many packages (treeio, phyloch, ips etc.) and not all packages will produce a tree structure that is compatible with downstream analyses in this tutorial's script.
