### ISSUE TITLE
Extant tree with node bars not generating 

### ISSUE THREAD

**Issue by avvypaks** [Taming-the-BEAST/FBD-tutorial#6]
Hi,
Greetings !!!

We have recently analyzed a mitogenome-based dataset of mammals to estimate the possible divergence time through a relaxed molecular clock approach. 

We used the FBD model as a tree prior, with six fossil calibration points in the BEAST 2 program. We are following the FBD tutorial (https://taming-the-beast.org/tutorials/FBD-tutorial/FBD-tutorial.pdf) for the analysis, however extant tree with node bars are not generated as described in Fig. 32 through strap package in R.

Warm Regards,
Avas Pakrashi
Senior Research Fellow
Zoological Survey of India

**Comment by laduplessis** [comment]
Please only raise issues directly related to the tutorial here, not your own research projects. I suggest you get in touch with the developers of the strap package. There is also a link to a strap tutorial within the FBD tutorial.

**Comment by avvypaks** [comment]
Thanks for your response.
