### ISSUE TITLE
how to you set the lognormal parameter?

### ISSUE THREAD

**Issue by liamxg** [Taming-the-BEAST/FBD-tutorial#9]
Dear @laduplessis,

how do you transform of ` mean: 45.5,  a standard deviation of 1.0` to ` mean: 8.5, a standard deviation of 1.0` in in Real Space? 

<img width="864" alt="image" src="https://github.com/Taming-the-BEAST/FBD-tutorial/assets/46078579/3351f981-6683-4caa-8bbb-a3e45c5b4bc1">

**Comment by jugne** [comment]
As you can see in the screenshot (it is also mentioned in the tutorial), there is an offset of 37. 37+8.5=45.5

**Comment by liamxg** [comment]
Dear @jugne,

Thanks. You are so kind.

Best,
Liam
